src/lib.rs, tests/assert_eq.rs
Fixes #10. Ensure that assert_eq can compile with comparable types.
=>  #10 - assert_eq! too strict with strings

src/lib.rs, tests/assert_ne.rs
Using `assert_ne!()` in a function that returns not `()` fails to build. This happens when functions use `assert!()` and friends for checks (e.g. preconditions) instead of strictly unit tests.
This PR fixes that and adds a small test case to demonstrate the issue and verify that the change works. The change just inverts an `if` and removes a `return`. I tested this with my project (where I encountered the issue) and it seems to work, but it would be nice to hear that this works on something larger with more diverse tests.
Example of a (relatively unimaginative) function which fails to build today:
```rust
fn not_zero(x: u32) -> u32 {
assert_ne!(x, 0);
x
};
```
(As an aside, the changes are much easier to glance over with `git diff -w`, since most of the changes are in indentation)
=> Allow assert_ne!() in functions returning values

src/lib.rs, tests/assert_eq.rs, tests/assert_ne.rs
This resolves #16. I've added tests as well.
=> Add trailing comma support in macros

Cargo.toml, src/lib.rs
This fixes issue #29.
Sorry for the inconvenience.
This makes output_vt100 silently fails when an error occurs while getting the standard output handle.
=> Prevent fail on Windows builds

.travis.yml, scripts/check, scripts/install
For #46 
- make sure the build fails correctly if any check fails
- ignore the existing `difference` audit warning
- break out installation and checking as scripts
=> ci: make travis fail on audit failure

CHANGELOG.md, src/lib.rs, tests/assert_eq.rs, tests/assert_ne.rs
=> Support unsized values in assertions

CHANGELOG.md, examples/pretty_assertion.rs, src/lib.rs, tests/assert_eq.rs, tests/assert_ne.rs, tests/pretty_string.rs
Closes #41
Some macro expansions were not hygenic, and ended up referencing the standard library `assert_eq` and `assert_ne`. This was masked in tests by statements such as `use pretty_assertions::assert_eq` which masked the stdlib macros in tests.
Updated tests to remove these `use` statements, and audited the existing macro code for non-`$crate` qualified paths.
=> Test and fix macro hygiene

scripts/check
Ref #44; now we no longer depend on `difference`, we can stop ignoring the `cargo audit` warning for it.
=> ci: clear cargo audit ignores

.github/workflows/check.yml, .gitignore
For #46 
Travis CI appears to be:
- migrating users to some sort of quota/credit based plan
- having technical difficulties during their migration to travis-ci.com
Currently builds are experiencing enough problems on Travis that porting them to Github is less effort.
=> ci: add github actions

.github/workflows/check.yml
For `cargo-audit` and `cargo-tarpaulin` (which still take a long time to install)
=> ci: cache cargo binary installations

README.md
Currently, the images only render when the readme is displayed on github - they're broken on other sites such as crates.io:
=> chore: make image urls in readme absolute

.github/workflows/check.yml, .github/workflows/publish.yml, scripts/publish
Before use, the `CARGO_LOGIN_TOKEN` secret should be set in the repo settings to an appropriate value.
=> ci: add crate publish workflow

.gitignore
To avoid `cargo publish` warning us that we have untracked files in our working directory.
=> ci: update gitignore

src/printer.rs
Inline diffing with the boundary of multiline chunks looks bad, and is counter-intuitive. For this reason, most diff implementations don't do it (such as Github).
We also shouldn't do this kind of inline diffing if there are more lines deleted preceding, or more lines inserted following, the boundary.
=> printer: do not print inline diff for multiline insert/delete chunks

src/lib.rs
Closes #69
Test and fix macro expansion in a `!#[no_implicit_prelude]` context
=> hygiene: test macros with no_implicit_prelude

.github/workflows/check.yml, CHANGELOG.md, pretty_assertions/Cargo.toml, pretty_assertions/src/lib.rs, pretty_assertions/tests/macros.rs, pretty_assertions_bench/Cargo.toml, scripts/check
Closes #80 
Inlines the existing top level implementation of stdlib's `assert_matches`, and links it into our existing display framework. The results look... okay. Patterns don't come with nice multiline displaying, so we're mostly diffing a value against a pattern - but just getting them displayed in red/green and on separate lines is still nice.
@gilescope this was your suggestion, so will leave open for a bit if you have any further thoughts?
=> feature: add assert_matches as unstable feature

CHANGELOG.md, README.md, pretty_assertions/Cargo.toml, pretty_assertions/src/lib.rs, pretty_assertions/src/printer.rs, pretty_assertions/tests/macros.rs, scripts/check
For #82 
Work in progress towards `no_std` support (will still require `alloc`). Things still to do:
=> feat: fix and test for no_std with alloc

CHANGELOG.md, pretty_assertions/Cargo.toml, pretty_assertions/LICENSE-APACHE, pretty_assertions/LICENSE-MIT, pretty_assertions_bench/Cargo.toml, scripts/check
Closes #86 
Includes license texts in the crate archive - these were omitted by mistake.
Also:
- Updates the license identifier to a valid SPDX identifier; use of `/` instead of ` OR ` is deprecated by cargo: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields.
- Prevent benchmarks from being accidentally published
=> chore: include license text in crate artefact

pretty_assertions/src/lib.rs, pretty_assertions/tests/macros.rs
As discussed in #24, pretty_assertion's `assert_eq` will escape line
breaks in multi-line strings, making diffs for them much harder to
read.
This commit introduces another variant, `assert_str_eq`, and the
associated `StrComparison`, which compares the raw strings, where
the newlines are not escaped.
Fixes #24
=> Add `assert_str_eq` macro for comparing "raw" strings

pretty_assertions/src/lib.rs, pretty_assertions/tests/macros.rs
This PR makes `assert_eq!(left, right)` automatically behave like `assert_str_eq!(left, right)` when both sides are str/String.
We could alternatively do this only if one or both strings contains `\n` if you prefer, as that's when the old behavior of `assert_eq!` is definitely worse; #24.
=> Automatically use StrComparison for comparing strings

pretty_assertions/src/printer.rs
Closes #96 
Turns out that we had assumed an invariant from the underlying `diff` library that does not, in fact, exist. We can receive an insertion followed by a deletion in the case where a trailing newline is deleted - for some reason the trailing newline deletion is not grouped with the previous deletion, and instead follows after the insertion on its own, despite there being no plain text in the middle.
It's a slightly odd looking diff, but I think it makes sense and is not worth special casing further. It's handled nicely by just removing our invariant check and letting the existing logic handle it.
=> fix: deleted trailing newline causes panic

.github/workflows/check.yml, pretty_assertions/Cargo.toml, pretty_assertions/src/lib.rs, pretty_assertions/src/printer.rs, pretty_assertions/tests/macros.rs
Fixes #101 
Technically a breaking change because `ansi_term::Style` is publicly-exported (due to the way the macros are constructed), but I would be very surprised if anyone was relying on it.
=> replace ansi_term with yansi

CHANGELOG.md, README.md, pretty_assertions/Cargo.toml, pretty_assertions/src/lib.rs, pretty_assertions/src/printer.rs
Also changes all repository references to reflect the recent organisation move, `colin-kiegel -> rust-pretty-assertions`
=> chore: prepare v1.3.0 release

pretty_assertions/Cargo.toml, pretty_assertions/src/lib.rs
As decided in [this discussion](https://github.com/rust-pretty-assertions/rust-pretty-assertions/pull/115#issuecomment-1623986652), we will remove this windows specific feature/logic as unused.
If anyone screams, we can reinstate after discussion of target environment.
=> chore: remove stale vt100/ctor dependencies

.github/workflows/check.yml, pretty_assertions/Cargo.toml, pretty_assertions/src/printer.rs
Updates yansi to 1.0.0-rc. Note that 1.0.0-rc is seen as semver compatible with 1.0.0 by Cargo, so no additional change would be necessary to get yansi 1.0 once it's released. 
The main advantages to the update is 1) automatic support for Windows, 2) fewer allocations by making use of lingering, and 3) pithier styling in general.
=> chore: update 'yansi' to 1.0.0-rc

pretty_assertions/Cargo.toml, pretty_assertions/src/printer.rs
Fixes the CI run for #130.
```console
error: use of deprecated method `yansi::Paint::clear`: renamed to `resetting()` due to conflicts with `Vec::clear()`.
The `clear()` method will be removed in a future release.
```
=> chore: rename deprecated yansi methods

pretty_assertions/Cargo.toml
This should make `assert_matches` visible on [docs.rs](https://docs.rs/pretty_assertions/latest/pretty_assertions/#macros).
=> chore: display feature-flagged docs on docs.rs

README.md
I wanted to do this and figured it'd help if it was more visible
=> docs: add tip to enforce using `pretty_assertions` macros over `std`

scripts/check, scripts/cover, scripts/install, scripts/publish
`/usr/bin/env bash` will search $PATH for `bash` and execute it instead of relying on it being installed in `/bin/bash`. E.g. on NixOS and several BSDs this is not the case.
=> build: Increase portability of shell scripts
